# Trophic model for gut data processing
This file is used to pre-process all data (especially Chia network and Thai Children data) into the format which is convenient for simulations.

In [1]:
########### Self-customized setting
import pandas as pd
import numpy as np

In [7]:
########### Load the metadata of HMP
metadata = pd.read_csv('./data/HMP_metadata.txt', delimiter='\t')
i_healthy_ids = metadata.loc[metadata['diagnosis']=='nonIBD', 'External ID']
metadata.head()

,Project,External ID,Participant ID,site_sub_coll,data_type,week_num,date_of_receipt,interval_days,visit_num,Research Project,...,FecalCal received at MGH:,Proteomics received at LBNL:,Stool Sample ID: Tube A (EtOH),Sample ID: Tube B (No preservative),Tube A and B received at Broad:,stool_id,smoking status,Number years smoked,Age when started smoking,How many cigarettes/cigars/etc. do you smoke per day?
0,G110131,CSM67UA2,C3001,C3001C15,metagenomics,28,2014-09-30,13,20,ibdmdb,...,No,No,SM-67UA2,SM-67UA3,No,NaN,NaN,NaN,NaN,NaN
1,G110162,CSM79HGP,C3001,C3001C20,metagenomics,38,2014-12-10,15,26,ibdmdb,...,No,No,SM-79HGP,SM-79HGQ,No,NaN,NaN,NaN,NaN,NaN
2,G110144,CSM5MCVN,C3002,C3002C9,metagenomics,16,2014-08-19,13,13,ibdmdb,...,No,No,SM-5MCVN,SM-5MCVO,No,NaN,NaN,NaN,NaN,NaN
3,G110126,CSM67UBH,C3002,C3002C14,metagenomics,26,2014-10-28,13,19,ibdmdb,...,No,No,SM-67UBH,SM-67UBI,No,NaN,NaN,NaN,NaN,NaN
4,G110174,CSM67UBN,C3002,C3002C17,metagenomics,32,2014-12-09,14,22,ibdmdb,...,No,No,SM-67UBN,SM-67UBO,No,NaN,NaN,NaN,NaN,NaN

In [36]:
########### Load the mapped metabolites and microbes from HMP to Chia network
metagenome = pd.read_csv('./data/HMP_metagenome_matched.txt', delimiter='\t')
metabolome = pd.read_csv('./data/HMP_metabolome_matched_wb.txt', delimiter='\t')
metagenome = metagenome[['Microbe_name', 'Chia_name', 'Chia_id', 'Match'] + list(i_healthy_ids.values)]
metabolome = metabolome[['Compound_name', 'Kegg_id', 'Chia_name', 'Chia_id', 'Method'] + list(i_healthy_ids.values)]

In [37]:
########### Select the microbial strains have a maped existence in the Chia network
#metagenome_mapped_in_Chia = metagenome[metagenome['Chia_id'] > 0]
metagenome_mapped_in_Chia = metagenome[metagenome['Match'] == 'T']
metagenome = metagenome_mapped_in_Chia.groupby('Chia_id').apply(np.sum).iloc[:,4:]
metagenome_ID = metagenome.reset_index()['Chia_id']
metagenome.head()

,CSM67UH7,CSM79HGZ,CSM79HP4,CSM7KOOH,CSMAG78W,HSM5MD5D,HSM67VFZ,HSM67VGA,HSM67VGG,HSM5MD6K,...,MSMB4LXW,MSMB4LZK,PSM7J14X,PSM7J156,PSM7J16Y,PSM7J1A2,PSM7J17X,PSM7J15M,PSM7J15U,PSMA265H
Chia_id,,,,,,,,,,,,,,,,,,,,,
9,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
31,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
33,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
38,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
46,0.586016,0.081073,0.047683,0.070263,0.0,0.009974,0.002312,0.030039,0.163099,0.0,...,0.0,0.0,0.024359,0.003352,0.105978,0.0,0.0,0.0,0.0,0.0

In [38]:
print('The microbial coverage in Chia is',len(metagenome_mapped_in_Chia) / len(metagenome))
print(len(metagenome),'OTUs are shrinked to ', len(metagenome))

The microbial coverage in Chia is 1.005050505050505
198 OTUs are shrinked to  198

In [39]:
########### Select all metabolites in the metabolome have a maped existence in the Chia network
#metabolome_mapped_in_Chia = metabolome[metabolome['Chia_id'] > 0]
metabolome_mapped_in_Chia = metabolome[metabolome['Chia_id'] > 0]
metabolome = metabolome_mapped_in_Chia.groupby('Chia_id').apply(np.sum).iloc[:,5:]
metabolome = metabolome[metagenome.columns]
metabolome_ID = metabolome.reset_index()['Chia_id']
metabolome.head()

,CSM67UH7,CSM79HGZ,CSM79HP4,CSM7KOOH,CSMAG78W,HSM5MD5D,HSM67VFZ,HSM67VGA,HSM67VGG,HSM5MD6K,...,MSMB4LXW,MSMB4LZK,PSM7J14X,PSM7J156,PSM7J16Y,PSM7J1A2,PSM7J17X,PSM7J15M,PSM7J15U,PSMA265H
Chia_id,,,,,,,,,,,,,,,,,,,,,
2006,9411758,12959742,9722867,9069,6546427,1961786,1847125,0,1556991,16568,...,9566,2129,9197805,666717,1618846,1306,66883,97941,24377936,1052989
2017,2015490,4464147,526995,388940,3580152,1846339,669945,0,937636,12396,...,0,93226,2962667,1045416,326677,8485,5071,2419149,2706315,696844
2018,4742057,7195326,3222882,109541,58417195,3096380,235927,0,301063,32604,...,9406,43130,462132,887,3082330,18268,436260,545999,29974931,2723935
2020,2124539,7765242,19510250,32089731,4086351,967941,3562517,0,222658,38179,...,14615,80247,5279411,631485,395403,0,2245,364572,1346936,1342514
2022,1379988,359569,1309,3538,1535294,2153905,2497408,0,1331238,8529,...,60406,18726,12458945,90810,269375,1064,5893,29068,8136919,500975

In [40]:
print('The metabolite coverage in Chia is',len(metabolome_mapped_in_Chia) / len(metabolome))
print(len(metabolome),'metabolites are shrinked to', len(metabolome))

The metabolite coverage in Chia is 1.0
92 metabolites are shrinked to 92

In [41]:
########### Load Chia network as net (containing information of metabolite consumption and production)
net = pd.read_csv('./data/pruned_chia_network.csv')
mean_net = net.groupby('microbes_ID').mean()
selfish_net = mean_net[mean_net.iloc[:,1] == 2]
i_selfish = selfish_net.index.values   #### i_selfish returns IDs of microbes don't generate byproducts
print(net.head())
print('###################################################################################################')

########### Load names of all nodes in the Chia network
names = pd.read_csv('./data/names_ID.txt',sep=': ')
names.set_index('IDs', inplace=True)
print(names.head())
print('###################################################################################################')

########### Load names of all nodes in the Chia network
#i_intake = pd.read_csv('nutrient_intake_ID_infact.txt',sep=': ')
i_intake = pd.read_csv('./data/nutrient_intake_ID.txt',sep=': ')
i_intake = i_intake['IDs'].values
print(i_intake)
print('###################################################################################################')

   metabolites_ID  microbes_ID  \
0            2001          896
1            2001          832
2            2001          831
3            2001          600
4            2001          571

   edge_types (2 represents intake, 3 represents secretion and 5 represents intake and secretion)
0                                                  2
1                                                  2
2                                                  2
3                                                  3
4                                                  3
###################################################################################################
                          Names
IDs
3    Acetivibrio cellulolyticus
4      Acetobacter pasteurianus
5      Acetohalobium arabaticum
6        Acholeplasma laidlawii
7      Achromobacter piechaudii
###################################################################################################
[2044 2060 2061 2064 2065 2068 2069 2072 2074 2079 2082 2094 2098 2149
 2161 2172 2174 2242 2157 2206]
###################################################################################################

/Users/tongwang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  # Remove the CWD from sys.path while we load stuff.
/Users/tongwang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [42]:
########### pickle all processed data which are useful for simulations
import pickle

pickle_out = open("Chia_network.pickle","wb")
pickle.dump([net, i_selfish, i_intake, names], pickle_out)
pickle_out.close()

pickle_out = open("data.pickle","wb")
pickle.dump([metagenome_ID, metagenome, metabolome_ID, metabolome], pickle_out)
pickle_out.close()